version: "3.5"

services:

  db:
    image: mongo
    ports: "27017:27017"
    volumes: "/data/db:/data/db"

  server:
    build:
      context: server
      dockerfile: Dockerfile

    ports: "8080:8080"
    