version: "2"

services:
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: proxy:80
      NGROK_AUTH: ${NGROK_AUTH}
    depends_on:
      - proxy

  proxy:
    image: matthewnitschke/fi-proxy:latest
    ports:
      - "80:80"

  db:
    logging:
      driver: none
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - "/data/db:/data/db"

  server:
    image: matthewnitschke/fi:latest
    ports:
      - "8080"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
    
networks:
  default:
    external:
      name: fi-network